"""
Script for matching property values of the exiftool-JSON retrieved from a test image
against a JSON object acting as IPTC Standard reference

"""
import os
import shutil
import yaml
import datetime
from scripts import ipmdchecker2 as ipmdchecker

currentdir = os.path.dirname(os.path.realpath(__file__))

CONFIGFP = currentdir + '/config/scriptsconfig.yml'
with open(CONFIGFP) as yaml_file1:
    scriptconfigs = yaml.safe_load(yaml_file1)

FILESDIR = currentdir + '/' + scriptconfigs['general']['filespathrel']
TESTRESULTSDIR = FILESDIR + 'testresults/'
LOGFP = TESTRESULTSDIR + 'testresults_all.txt'

# Test2 specific directories
TEST2DIR = FILESDIR + 'test2/'
CACHE2DIR = FILESDIR + 'cache/test2/'
BACKUP2DIR = FILESDIR + 'backup/test2/'




def run_test2(testimgfn: str) -> None:
    """Runs IPTC Photo Metadata Interoperability Test #2 with a single image file

    :param testimgfn: file name of the to be tested image file
    :return: nothing
    """
    coretestimgfn = os.path.splitext(testimgfn)[0]
    testimgfp = TEST2DIR + testimgfn
    testjsonfp = CACHE2DIR + coretestimgfn + '.json'
    testresults1fp = TESTRESULTSDIR + coretestimgfn + '.txt'
    backupimgfp = BACKUP2DIR + testimgfn

    ipmdchecker.readpmd_exiftool(testimgfp, testjsonfp)
    if os.path.isfile(testjsonfp):
        msg = 'Tested(2) JSON file of image: ' + testimgfn
        print(msg)
        ipmdchecker.append_line2file(msg, LOGFP)
        ipmdchecker.append_line2file(msg, testresults1fp)
        msg = 'Tested on: ' + datetime.datetime.now().astimezone().replace(microsecond=0).isoformat()
        print(msg)
        ipmdchecker.append_line2file(msg, LOGFP)
        ipmdchecker.append_line2file(msg, testresults1fp)

        ipmdchecker.check_mainpmd(testjsonfp, testresults1fp, comparevalues=True)
        ipmdchecker.append_line2file('***** TEST FINISHED *****', testresults1fp)
        shutil.move(testimgfp, backupimgfp)
    else:
        print(f'No JSON file generated by ExifTool for {testjsonfp}')


def testdummy1():
    testfilename = '_test2_example1'
    testfp = '../files/cache/test2/' + testfilename + '.json'
    testresults1fp = TESTRESULTSDIR + testfilename + '.txt'
    ipmdchecker.append_line2file('Tested JSON file: ' + testfp, LOGFP)
    ipmdchecker.append_line2file('Tested JSON file: ' + testfp, testresults1fp)
    ipmdchecker.check_mainpmd(testfp, testresults1fp, comparevalues=True)


if __name__ == '__main__':

    DEV: bool = False

    if DEV:
        testdummy1()
    else:
        foundtest2images = ipmdchecker.find_testfiles(TEST2DIR)
        print(foundtest2images)
        for testimgfn in foundtest2images:
            run_test2(testimgfn)
